[package]
name = "froodi-compile-core"
version = "0.0.0"
edition = "2021"
authors = ["Desiders"]
license = "Apache-2.0"
repository = "https://github.com/Desiders/froodi"
publish = false

description = "Registration IR and graph compiler of the experimental compile-time Froodi engine"

rust-version = "1.85"

[dependencies]
