[package]
name = "froodi-public-consumer"
default-run = "froodi-public-consumer"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[[bin]]
name = "static-scope"
path = "src/bin/static_scope.rs"
required-features = ["unified"]

[features]
compiled = ["di/compiled"]
async = ["di/async", "dep:tokio"]
unified = ["dep:compiled-enabler"]

[dependencies]
di = { package = "froodi", version = "=1.0.0-beta.18" }
tokio = { version = "1", features = ["rt", "macros"], optional = true }
compiled-enabler = { path = "enabler", optional = true }
