#!/usr/bin/env python3
"""Generates graphs.rs: the same graphs written for current Froodi and the compile-time engine.

Run from this directory: python3 generate.py > graphs.rs
"""

DEPTH = 100
WIDE = 16


def types():
    out = ["#[derive(Clone)]", "pub struct S0;"]
    for i in range(1, DEPTH):
        # The previous link is stored erased: a 100-deep `Arc<Arc<...>>` type overflows drop-check.
        out.append(f"pub struct S{i}(pub Arc<dyn Send + Sync>);")
    out.append("#[derive(Clone)]")
    out.append("pub struct T0;")
    for i in range(1, DEPTH):
        out.append(f"pub struct T{i}(pub Box<dyn Send + Sync>);")
    out.append(f"pub struct Wide(pub [u8; {WIDE}]);")
    out.append("pub struct Plugin(pub u8);")
    out.append("pub struct Host(pub Arc<Plugin>);")
    return "\n".join(out)


def factories():
    out = [
        "pub fn s0() -> Result<S0, InstantiateErrorKind> { Ok(S0) }",
        "pub fn t0() -> Result<T0, InstantiateErrorKind> { Ok(T0) }",
    ]
    for i in range(1, DEPTH):
        out.append(f"pub fn s{i}(Inject(p): Inject<S{i - 1}>) -> Result<S{i}, InstantiateErrorKind> {{ Ok(S{i}(p)) }}")
        out.append(f"pub fn t{i}(InjectTransient(p): InjectTransient<T{i - 1}>) -> Result<T{i}, InstantiateErrorKind> {{ Ok(T{i}(Box::new(p))) }}")
    params = ", ".join(f"Inject(_{i}): Inject<S0>" for i in range(WIDE))
    out.append(f"pub fn wide({params}) -> Result<Wide, InstantiateErrorKind> {{ Ok(Wide([0; {WIDE}])) }}")
    out.append("pub fn host(Inject(p): Inject<Plugin>) -> Result<Host, InstantiateErrorKind> { Ok(Host(p)) }")
    return "\n        ".join(out)


def provides(prefix):
    return ", ".join(f"provide({prefix}{i})" for i in range(DEPTH))


def module(name, engine):
    return f"""
pub mod {name} {{
    use super::*;
    use {engine}::{{registry, Container, DefaultScope::*, Inject, InjectTransient, InstantiateErrorKind}};

    mod f {{
        use super::*;
        {factories()}
    }}

    pub fn chain(app: bool) -> Container {{
        if app {{
            Container::new(registry! {{ scope(App) [ {provides("f::s")} ] }})
        }} else {{
            Container::new(registry! {{ scope(Request) [ {provides("f::s")} ] }})
        }}
    }}

    pub fn transient_chain() -> Container {{
        Container::new(registry! {{ scope(App) [ {provides("f::t")} ] }})
    }}

    pub fn wide() -> Container {{
        Container::new(registry! {{ scope(App) [ provide(f::s0), provide(f::wide) ] }})
    }}

    pub fn captured() -> Container {{
        let label = Arc::new(String::from("captured"));
        Container::new(registry! {{ scope(Request) [ provide(move || Ok::<_, InstantiateErrorKind>(label.clone())) ] }})
    }}
"""


def indexed():
    return f"""
    /// The same graphs erased with `into_runtime()`: the indexed backend.
    pub mod indexed {{
        use super::*;

        pub fn chain(app: bool) -> Container {{
            let registry = if app {{
                registry! {{ scope(App) [ {provides("f::s")} ] }}.into_runtime()
            }} else {{
                registry! {{ scope(Request) [ {provides("f::s")} ] }}.into_runtime()
            }};
            Container::new(registry! {{ extend(registry) }})
        }}

        pub fn transient_chain() -> Container {{
            Container::new(registry! {{ extend(registry! {{ scope(App) [ {provides("f::t")} ] }}.into_runtime()) }})
        }}

        pub fn wide() -> Container {{
            Container::new(registry! {{ extend(registry! {{ scope(App) [ provide(f::s0), provide(f::wide) ] }}.into_runtime()) }})
        }}

        pub fn captured() -> Container {{
            let label = Arc::new(String::from("captured"));
            Container::new(registry! {{ extend(registry! {{ scope(Request) [ provide(move || Ok::<_, InstantiateErrorKind>(label.clone())) ] }}.into_runtime()) }})
        }}
    }}

    /// One runtime registration inside a static graph, reached through a declared boundary.
    pub fn mixed() -> Container {{
        let plugins = registry! {{ scope(App) [ provide(|| Ok::<_, InstantiateErrorKind>(Plugin(1))) ] }}.into_runtime();
        Container::new(registry! {{
            scope(App) [ provide(froodi_compile::runtime::<Plugin>()), provide(f::host) ],
            extend(plugins),
        }})
    }}
"""


HEADER = """//! Generated by `generate.py`; do not edit by hand.
//!
//! Current Froodi against the compile-time engine's two backends (issues #59, #64):
//!
//! - `froodi`: the current runtime engine;
//! - `direct`: level B, static edges are direct calls to the provider's factory;
//! - `indexed`: level A, the same registry erased with `into_runtime()`, edges go through the
//!   construction table by registration id with a checked downcast.
#![allow(clippy::all, clippy::pedantic, dead_code)]

use std::sync::Arc;
"""

import pathlib
import subprocess

source = "\n".join(
    [HEADER, types(), module("froodi_engine", "froodi") + "}", module("compile_engine", "froodi_compile") + indexed() + "}"]
)
# Format with the workspace rustfmt.toml so `cargo fmt` leaves the output unchanged.
config = pathlib.Path(__file__).resolve().parents[3] / "rustfmt.toml"
formatted = subprocess.run(
    ["rustfmt", "--edition", "2021", "--config-path", str(config), "--emit", "stdout"],
    input=source, capture_output=True, text=True, check=True,
).stdout
print(formatted, end="")
