[package]
name = "dptree"
version = "1.0.0"
edition = "2024"

[dependencies]
froodi = { path = "../../froodi", features = ["dptree"] }

tokio = { version = "1.36", features = ["rt", "macros"] }
dptree = { version = "0.5" }
