[package]
name = "froodi-compile-build"
version = "0.0.0"
edition = "2021"
authors = ["Desiders"]
license = "Apache-2.0"
repository = "https://github.com/Desiders/froodi"
publish = false

description = "`build.rs` staging experiments of the experimental compile-time Froodi engine"

rust-version = "1.85"

[dependencies]
proc-macro2 = { version = "1", features = ["span-locations"] }
quote = "1"
syn = { version = "2", features = ["full", "visit"] }
