[package]
name = "froodi-compile"
version = "0.0.0"
edition = "2021"
authors = ["Desiders"]
license = "Apache-2.0"
repository = "https://github.com/Desiders/froodi"
publish = false

description = "Experimental compile-time Froodi engine (facade)"

rust-version = "1.85"

[features]
default = ["std", "thread_safe"]

std = ["froodi-compile-runtime/std"]
thread_safe = ["froodi-compile-runtime/thread_safe"]
lock-parking-lot = ["froodi-compile-runtime/lock-parking-lot"]
lock-spin = ["froodi-compile-runtime/lock-spin"]
async = ["froodi-compile-runtime/async"]

[dependencies]
froodi-compile-core = { path = "../froodi-compile-core" }
froodi-compile-macros = { path = "../froodi-compile-macros" }
froodi-compile-runtime = { path = "../froodi-compile-runtime", default-features = false }

[dev-dependencies]
froodi = { path = "../froodi" }
trybuild = "1"
