[package]
name = "async_finalizer"
version = "1.0.0"
edition = "2024"

[dependencies]
froodi = { path = "../../froodi", features = ["async"] }

tokio = { version = "1.36", features = ["rt", "macros"] }
