[package]
name = "froodi-compile-macros"
version = "0.0.0"
edition = "2021"
authors = ["Desiders"]
license = "Apache-2.0"
repository = "https://github.com/Desiders/froodi"
publish = false

description = "`registry!` frontend of the experimental compile-time Froodi engine"

rust-version = "1.85"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
